name: b2w_marketplace
description: A new Flutter project. Created by Slidy

publish_to: 'none' 

version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.0+1

dev_dependencies:
  mockito: ^4.1.1
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
  
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: pt_BR # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
